#PBS -N Kraken2_16s
#PBS -l nodes=1:ppn=6
#PBS -l pmem=5gb
#PBS -l walltime=10:00:00
#PBS -A mah546_a_g_sc_default
#PBS -j oe
#PBS -M m0rris@psu.edu
#PBS -m abe

KRAKEN2=/storage/home/mua447/work/CBIOS_project/sw/kraken2
DBNAME=/gpfs/group/mah546/default/personal/Morris/CBIOS/16S_RDP_k2db
OUTPUT=/storage/home/mua447/work/CBIOS_project/output
DATA=/gpfs/group/mah546/default/personal/Morris/CBIOS/data/16s

for i in {1..670}
do
SRA=$(sed -n $( echo $i )p $DATA/SRA_16s_list.txt)
$KRAKEN2/kraken2 --threads 6 --report $OUTPUT/report_16s_$SRA.txt --db $DBNAME $DATA/$SRA.fastq > $OUTPUT/results_16s_$SRA.txt
SRA=0
echo $i
done
